### ISSUE TITLE
can't find crate when import subdir of git url

### ISSUE THREAD

**Issue by justcode740** [shuklaayush/noir-bigint#10]
i try to import this lib by the readme instruction but get `Error: cannot find src directory in path /home/<user>/nargo/github.com/shuklaayush/noir-bigintv0.1.0`, think there's something wrong with subdir search or is there any integration test been done on this?

here, think should search for all folder with nargo.toml in multiple crate case: https://github.com/noir-lang/noir/blob/fd291971f2060438c4b529e4cb5b5911a9939418/crates/nargo/src/lib.rs#L34-L42

nargo --version output
nargo 0.7.1 (git version hash: d0110e27e225290af05134be4c9e490c79e3cb9a, is dirty: false)

**Comment by shuklaayush** [comment]
Depends on https://github.com/noir-lang/noir/issues/2107

**Comment by shuklaayush** [comment]
This should work now. See
https://github.com/shuklaayush/noir-bigint?tab=readme-ov-file#installation
