### ISSUE TITLE
Test case cannot be run.

### ISSUE THREAD

**Issue by Huang-Xinzhong** [shuklaayush/noir-bigint#15]
I pulled the code and ran the test case in the root directory with an error message
`
Error: Nargo.toml is badly formed, could not parse.

 data did not match any variant of untagged enum Manifest

Caused by:
    data did not match any variant of untagged enum Manifest

Location:
    crates/nargo_cli/src/cli/mod.rs:74:5
`

I am using Nargo version 0.9.0
`
nargo 0.9.0 (git version hash: 970c18ee29e37d35e39169005e629deed8b30b6e, is dirty: false)
`

**Comment by shuklaayush** [comment]
This should be fixed in the latest version
